var agent_data = [
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 1,
    "re": 3,
    "trial_n": 1,
    "rews1a": 1,
    "rews1b": 0,
    "rews2a": 3,
    "rews2b": 0,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 2,
    "trial_n": 2,
    "rews1a": 1,
    "rews1b": -3,
    "rews2a": 2,
    "rews2b": -4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 2,
    "trial_n": 3,
    "rews1a": 1,
    "rews1b": -5,
    "rews2a": 2,
    "rews2b": -5,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 4,
    "rews1a": 2,
    "rews1b": -4,
    "rews2a": 2,
    "rews2b": -5,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 1,
    "re": 4,
    "trial_n": 5,
    "rews1a": 2,
    "rews1b": -3,
    "rews2a": 4,
    "rews2b": -3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 4,
    "trial_n": 6,
    "rews1a": 2,
    "rews1b": -3,
    "rews2a": 4,
    "rews2b": -4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 7,
    "rews1a": 2,
    "rews1b": -4,
    "rews2a": 2,
    "rews2b": -3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -4,
    "trial_n": 8,
    "rews1a": 3,
    "rews1b": -4,
    "rews2a": 0,
    "rews2b": -3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -4,
    "trial_n": 9,
    "rews1a": 2,
    "rews1b": -4,
    "rews2a": 0,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 10,
    "rews1a": 1,
    "rews1b": -5,
    "rews2a": 0,
    "rews2b": -3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 11,
    "rews1a": 1,
    "rews1b": -3,
    "rews2a": -1,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": 0,
    "trial_n": 12,
    "rews1a": 0,
    "rews1b": -2,
    "rews2a": -1,
    "rews2b": -3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": -3,
    "trial_n": 13,
    "rews1a": 0,
    "rews1b": -2,
    "rews2a": -1,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -2,
    "trial_n": 14,
    "rews1a": 1,
    "rews1b": -2,
    "rews2a": 0,
    "rews2b": -2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 15,
    "rews1a": 1,
    "rews1b": -3,
    "rews2a": 1,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -2,
    "trial_n": 16,
    "rews1a": 1,
    "rews1b": -2,
    "rews2a": 1,
    "rews2b": -1,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 3,
    "trial_n": 17,
    "rews1a": 3,
    "rews1b": -2,
    "rews2a": 3,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 4,
    "trial_n": 18,
    "rews1a": 4,
    "rews1b": -4,
    "rews2a": 3,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 4,
    "trial_n": 19,
    "rews1a": 4,
    "rews1b": -4,
    "rews2a": 2,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -3,
    "trial_n": 20,
    "rews1a": 4,
    "rews1b": -3,
    "rews2a": 2,
    "rews2b": -1,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 21,
    "rews1a": 2,
    "rews1b": -3,
    "rews2a": 1,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 22,
    "rews1a": 2,
    "rews1b": -2,
    "rews2a": 0,
    "rews2b": 0,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 23,
    "rews1a": 2,
    "rews1b": -2,
    "rews2a": -1,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -3,
    "trial_n": 24,
    "rews1a": 2,
    "rews1b": -3,
    "rews2a": -1,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": 0,
    "trial_n": 25,
    "rews1a": 0,
    "rews1b": -3,
    "rews2a": -1,
    "rews2b": -1,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -3,
    "trial_n": 26,
    "rews1a": 0,
    "rews1b": -3,
    "rews2a": -1,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 0,
    "trial_n": 27,
    "rews1a": 0,
    "rews1b": -4,
    "rews2a": -1,
    "rews2b": -4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 0,
    "trial_n": 28,
    "rews1a": -1,
    "rews1b": -4,
    "rews2a": 0,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": -2,
    "trial_n": 29,
    "rews1a": 0,
    "rews1b": -3,
    "rews2a": 1,
    "rews2b": -2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 30,
    "rews1a": 1,
    "rews1b": -3,
    "rews2a": 0,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -2,
    "trial_n": 31,
    "rews1a": 2,
    "rews1b": -2,
    "rews2a": -1,
    "rews2b": -2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -3,
    "trial_n": 32,
    "rews1a": 1,
    "rews1b": -3,
    "rews2a": -2,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 33,
    "rews1a": 1,
    "rews1b": -3,
    "rews2a": -2,
    "rews2b": -2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 0,
    "trial_n": 34,
    "rews1a": 0,
    "rews1b": -2,
    "rews2a": -2,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 0,
    "trial_n": 35,
    "rews1a": 0,
    "rews1b": -3,
    "rews2a": -2,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -3,
    "trial_n": 36,
    "rews1a": -1,
    "rews1b": -3,
    "rews2a": -1,
    "rews2b": -2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -4,
    "trial_n": 37,
    "rews1a": -1,
    "rews1b": -4,
    "rews2a": -1,
    "rews2b": -2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -3,
    "trial_n": 38,
    "rews1a": 0,
    "rews1b": -3,
    "rews2a": 0,
    "rews2b": -1,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 0,
    "trial_n": 39,
    "rews1a": 0,
    "rews1b": -3,
    "rews2a": 0,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 1,
    "trial_n": 40,
    "rews1a": 0,
    "rews1b": -3,
    "rews2a": 1,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 41,
    "rews1a": 1,
    "rews1b": -4,
    "rews2a": 1,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 42,
    "rews1a": 2,
    "rews1b": -3,
    "rews2a": 0,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -4,
    "trial_n": 43,
    "rews1a": 2,
    "rews1b": -4,
    "rews2a": -1,
    "rews2b": -2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 44,
    "rews1a": 2,
    "rews1b": -4,
    "rews2a": 0,
    "rews2b": -2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 45,
    "rews1a": 2,
    "rews1b": -5,
    "rews2a": 0,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 46,
    "rews1a": 2,
    "rews1b": -4,
    "rews2a": 1,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -5,
    "trial_n": 47,
    "rews1a": 1,
    "rews1b": -5,
    "rews2a": 0,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -4,
    "trial_n": 48,
    "rews1a": 0,
    "rews1b": -4,
    "rews2a": 0,
    "rews2b": -2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 0,
    "trial_n": 49,
    "rews1a": 0,
    "rews1b": -2,
    "rews2a": 0,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 1,
    "trial_n": 50,
    "rews1a": 0,
    "rews1b": -2,
    "rews2a": 1,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": -3,
    "trial_n": 51,
    "rews1a": 0,
    "rews1b": -2,
    "rews2a": 1,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 2,
    "trial_n": 52,
    "rews1a": 0,
    "rews1b": -2,
    "rews2a": 2,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -3,
    "trial_n": 53,
    "rews1a": 1,
    "rews1b": -3,
    "rews2a": 2,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -3,
    "trial_n": 54,
    "rews1a": 1,
    "rews1b": -3,
    "rews2a": 3,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -2,
    "trial_n": 55,
    "rews1a": 0,
    "rews1b": -2,
    "rews2a": 4,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 4,
    "trial_n": 56,
    "rews1a": -1,
    "rews1b": -2,
    "rews2a": 4,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -3,
    "trial_n": 57,
    "rews1a": -1,
    "rews1b": -3,
    "rews2a": 4,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 3,
    "trial_n": 58,
    "rews1a": -1,
    "rews1b": -3,
    "rews2a": 3,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 3,
    "trial_n": 59,
    "rews1a": -2,
    "rews1b": -3,
    "rews2a": 3,
    "rews2b": -4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 2,
    "trial_n": 60,
    "rews1a": -2,
    "rews1b": -4,
    "rews2a": 2,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -4,
    "trial_n": 61,
    "rews1a": -1,
    "rews1b": -4,
    "rews2a": 4,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -3,
    "trial_n": 62,
    "rews1a": 0,
    "rews1b": -3,
    "rews2a": 5,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 1,
    "re": 5,
    "trial_n": 63,
    "rews1a": 0,
    "rews1b": -1,
    "rews2a": 5,
    "rews2b": 0,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 3,
    "trial_n": 64,
    "rews1a": -1,
    "rews1b": -1,
    "rews2a": 3,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 4,
    "trial_n": 65,
    "rews1a": -2,
    "rews1b": 0,
    "rews2a": 4,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -2,
    "trial_n": 66,
    "rews1a": -2,
    "rews1b": 0,
    "rews2a": 5,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 5,
    "trial_n": 67,
    "rews1a": -3,
    "rews1b": 0,
    "rews2a": 5,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 3,
    "trial_n": 68,
    "rews1a": -3,
    "rews1b": 1,
    "rews2a": 3,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": 0,
    "trial_n": 69,
    "rews1a": -2,
    "rews1b": 0,
    "rews2a": 4,
    "rews2b": 1,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 3,
    "trial_n": 70,
    "rews1a": -3,
    "rews1b": -1,
    "rews2a": 3,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -1,
    "trial_n": 71,
    "rews1a": -3,
    "rews1b": -1,
    "rews2a": 5,
    "rews2b": 1,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 4,
    "trial_n": 72,
    "rews1a": -3,
    "rews1b": -2,
    "rews2a": 4,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 5,
    "trial_n": 73,
    "rews1a": -2,
    "rews1b": -2,
    "rews2a": 5,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 5,
    "trial_n": 74,
    "rews1a": -2,
    "rews1b": -2,
    "rews2a": 5,
    "rews2b": 2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 5,
    "trial_n": 75,
    "rews1a": -3,
    "rews1b": 0,
    "rews2a": 5,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 4,
    "trial_n": 76,
    "rews1a": -2,
    "rews1b": 1,
    "rews2a": 4,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 1,
    "re": 3,
    "trial_n": 77,
    "rews1a": -2,
    "rews1b": 2,
    "rews2a": 3,
    "rews2b": 3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 4,
    "trial_n": 78,
    "rews1a": -1,
    "rews1b": 1,
    "rews2a": 4,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -1,
    "trial_n": 79,
    "rews1a": -1,
    "rews1b": 1,
    "rews2a": 4,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 5,
    "trial_n": 80,
    "rews1a": -1,
    "rews1b": 1,
    "rews2a": 5,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": 3,
    "trial_n": 81,
    "rews1a": -2,
    "rews1b": 2,
    "rews2a": 4,
    "rews2b": 3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 5,
    "trial_n": 82,
    "rews1a": -2,
    "rews1b": 3,
    "rews2a": 5,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 5,
    "trial_n": 83,
    "rews1a": -1,
    "rews1b": 2,
    "rews2a": 4,
    "rews2b": 5,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": 5,
    "trial_n": 84,
    "rews1a": -2,
    "rews1b": 3,
    "rews2a": 3,
    "rews2b": 5,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 4,
    "trial_n": 85,
    "rews1a": 0,
    "rews1b": 2,
    "rews2a": 4,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 5,
    "trial_n": 86,
    "rews1a": 0,
    "rews1b": 1,
    "rews2a": 4,
    "rews2b": 5,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 87,
    "rews1a": 0,
    "rews1b": 1,
    "rews2a": 5,
    "rews2b": 4,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 5,
    "trial_n": 88,
    "rews1a": -1,
    "rews1b": 1,
    "rews2a": 5,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -1,
    "trial_n": 89,
    "rews1a": -1,
    "rews1b": 1,
    "rews2a": 5,
    "rews2b": 5,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 5,
    "trial_n": 90,
    "rews1a": -2,
    "rews1b": 2,
    "rews2a": 5,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 4,
    "trial_n": 91,
    "rews1a": -2,
    "rews1b": 2,
    "rews2a": 4,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 1,
    "re": 3,
    "trial_n": 92,
    "rews1a": -2,
    "rews1b": 2,
    "rews2a": 3,
    "rews2b": 4,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 5,
    "trial_n": 93,
    "rews1a": -2,
    "rews1b": 3,
    "rews2a": 5,
    "rews2b": 5,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -2,
    "trial_n": 94,
    "rews1a": -2,
    "rews1b": 4,
    "rews2a": 4,
    "rews2b": 5,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 1,
    "re": 4,
    "trial_n": 95,
    "rews1a": -2,
    "rews1b": 4,
    "rews2a": 4,
    "rews2b": 5,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": 5,
    "trial_n": 96,
    "rews1a": -3,
    "rews1b": 5,
    "rews2a": 5,
    "rews2b": 5,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 5,
    "trial_n": 97,
    "rews1a": -3,
    "rews1b": 3,
    "rews2a": 5,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 4,
    "trial_n": 98,
    "rews1a": -2,
    "rews1b": 2,
    "rews2a": 4,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 3,
    "trial_n": 99,
    "rews1a": -2,
    "rews1b": 2,
    "rews2a": 3,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": 2,
    "trial_n": 100,
    "rews1a": -2,
    "rews1b": 2,
    "rews2a": 3,
    "rews2b": 4,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 101,
    "rews1a": -4,
    "rews1b": 2,
    "rews2a": 3,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": 2,
    "trial_n": 102,
    "rews1a": -5,
    "rews1b": 2,
    "rews2a": 2,
    "rews2b": 3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -4,
    "trial_n": 103,
    "rews1a": -4,
    "rews1b": 3,
    "rews2a": 4,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": 2,
    "trial_n": 104,
    "rews1a": -4,
    "rews1b": 2,
    "rews2a": 3,
    "rews2b": 3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 105,
    "rews1a": -4,
    "rews1b": 2,
    "rews2a": 3,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 5,
    "trial_n": 106,
    "rews1a": -3,
    "rews1b": 3,
    "rews2a": 1,
    "rews2b": 5,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 107,
    "rews1a": -2,
    "rews1b": 2,
    "rews2a": 1,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 1,
    "re": 2,
    "trial_n": 108,
    "rews1a": -3,
    "rews1b": 2,
    "rews2a": 2,
    "rews2b": 4,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 109,
    "rews1a": -2,
    "rews1b": 0,
    "rews2a": 2,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 2,
    "trial_n": 110,
    "rews1a": -1,
    "rews1b": 1,
    "rews2a": 1,
    "rews2b": 2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -1,
    "trial_n": 111,
    "rews1a": -1,
    "rews1b": 1,
    "rews2a": 1,
    "rews2b": 2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 3,
    "trial_n": 112,
    "rews1a": -1,
    "rews1b": 1,
    "rews2a": 0,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": 3,
    "trial_n": 113,
    "rews1a": -1,
    "rews1b": 0,
    "rews2a": 1,
    "rews2b": 3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 114,
    "rews1a": -1,
    "rews1b": -1,
    "rews2a": 2,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 3,
    "trial_n": 115,
    "rews1a": -1,
    "rews1b": -2,
    "rews2a": 1,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 116,
    "rews1a": 0,
    "rews1b": -2,
    "rews2a": 1,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -2,
    "trial_n": 117,
    "rews1a": 0,
    "rews1b": -2,
    "rews2a": 1,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 118,
    "rews1a": 1,
    "rews1b": 0,
    "rews2a": 0,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 3,
    "trial_n": 119,
    "rews1a": 1,
    "rews1b": 1,
    "rews2a": 0,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 3,
    "trial_n": 120,
    "rews1a": 2,
    "rews1b": 2,
    "rews2a": 0,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 121,
    "rews1a": 2,
    "rews1b": 2,
    "rews2a": 0,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 1,
    "re": -2,
    "trial_n": 122,
    "rews1a": 4,
    "rews1b": 2,
    "rews2a": -2,
    "rews2b": 5,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": 5,
    "trial_n": 123,
    "rews1a": 4,
    "rews1b": 3,
    "rews2a": -3,
    "rews2b": 5,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 5,
    "trial_n": 124,
    "rews1a": 4,
    "rews1b": 4,
    "rews2a": -3,
    "rews2b": 5,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 5,
    "trial_n": 125,
    "rews1a": 4,
    "rews1b": 5,
    "rews2a": -4,
    "rews2b": 5,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 126,
    "rews1a": 4,
    "rews1b": 5,
    "rews2a": -3,
    "rews2b": 4,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 5,
    "trial_n": 127,
    "rews1a": 5,
    "rews1b": 5,
    "rews2a": -3,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": -4,
    "trial_n": 128,
    "rews1a": 5,
    "rews1b": 5,
    "rews2a": -4,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 5,
    "trial_n": 129,
    "rews1a": 5,
    "rews1b": 5,
    "rews2a": -4,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 3,
    "trial_n": 130,
    "rews1a": 3,
    "rews1b": 4,
    "rews2a": -4,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 4,
    "trial_n": 131,
    "rews1a": 2,
    "rews1b": 4,
    "rews2a": -3,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 132,
    "rews1a": 1,
    "rews1b": 3,
    "rews2a": -4,
    "rews2b": 4,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 133,
    "rews1a": 0,
    "rews1b": 3,
    "rews2a": -4,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": -4,
    "trial_n": 134,
    "rews1a": 0,
    "rews1b": 4,
    "rews2a": -4,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": -5,
    "trial_n": 135,
    "rews1a": 0,
    "rews1b": 5,
    "rews2a": -5,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": -4,
    "trial_n": 136,
    "rews1a": 0,
    "rews1b": 5,
    "rews2a": -4,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": -5,
    "trial_n": 137,
    "rews1a": -1,
    "rews1b": 3,
    "rews2a": -5,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": 4,
    "trial_n": 138,
    "rews1a": -1,
    "rews1b": 4,
    "rews2a": -5,
    "rews2b": 3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": -2,
    "trial_n": 139,
    "rews1a": -2,
    "rews1b": 3,
    "rews2a": -4,
    "rews2b": 2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 3,
    "trial_n": 140,
    "rews1a": -2,
    "rews1b": 3,
    "rews2a": -3,
    "rews2b": 2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": -3,
    "trial_n": 141,
    "rews1a": -2,
    "rews1b": 3,
    "rews2a": -3,
    "rews2b": 2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 3,
    "trial_n": 142,
    "rews1a": -1,
    "rews1b": 3,
    "rews2a": -3,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": 1,
    "trial_n": 143,
    "rews1a": -1,
    "rews1b": 4,
    "rews2a": -2,
    "rews2b": 1,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 5,
    "trial_n": 144,
    "rews1a": -2,
    "rews1b": 5,
    "rews2a": -4,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": 1,
    "trial_n": 145,
    "rews1a": -3,
    "rews1b": 5,
    "rews2a": -4,
    "rews2b": 1,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 4,
    "trial_n": 146,
    "rews1a": -3,
    "rews1b": 4,
    "rews2a": -5,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": -2,
    "trial_n": 147,
    "rews1a": -2,
    "rews1b": 4,
    "rews2a": -3,
    "rews2b": 1,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 3,
    "trial_n": 148,
    "rews1a": -1,
    "rews1b": 3,
    "rews2a": -3,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": 0,
    "trial_n": 149,
    "rews1a": -1,
    "rews1b": 2,
    "rews2a": -2,
    "rews2b": 0,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 2,
    "trial_n": 150,
    "rews1a": 0,
    "rews1b": 2,
    "rews2a": -2,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": -3,
    "trial_n": 151,
    "rews1a": 1,
    "rews1b": 2,
    "rews2a": -3,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 2,
    "trial_n": 152,
    "rews1a": 0,
    "rews1b": 2,
    "rews2a": -3,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 3,
    "trial_n": 153,
    "rews1a": 1,
    "rews1b": 3,
    "rews2a": -2,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": 4,
    "trial_n": 154,
    "rews1a": -1,
    "rews1b": 4,
    "rews2a": -2,
    "rews2b": -2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": 0,
    "trial_n": 155,
    "rews1a": 0,
    "rews1b": 4,
    "rews2a": -2,
    "rews2b": -3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 4,
    "trial_n": 156,
    "rews1a": -1,
    "rews1b": 4,
    "rews2a": -2,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": -2,
    "trial_n": 157,
    "rews1a": -1,
    "rews1b": 3,
    "rews2a": -3,
    "rews2b": -2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": -1,
    "trial_n": 158,
    "rews1a": -1,
    "rews1b": 2,
    "rews2a": -2,
    "rews2b": -1,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 2,
    "trial_n": 159,
    "rews1a": -2,
    "rews1b": 2,
    "rews2a": -2,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 2,
    "trial_n": 160,
    "rews1a": -1,
    "rews1b": 2,
    "rews2a": -3,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 2,
    "trial_n": 161,
    "rews1a": -2,
    "rews1b": 2,
    "rews2a": -3,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": 1,
    "trial_n": 162,
    "rews1a": -2,
    "rews1b": 1,
    "rews2a": -2,
    "rews2b": -3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": 0,
    "trial_n": 163,
    "rews1a": -2,
    "rews1b": 0,
    "rews2a": -2,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -1,
    "trial_n": 164,
    "rews1a": -2,
    "rews1b": -1,
    "rews2a": -1,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -2,
    "trial_n": 165,
    "rews1a": -2,
    "rews1b": -1,
    "rews2a": -1,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -1,
    "trial_n": 166,
    "rews1a": -1,
    "rews1b": -2,
    "rews2a": -2,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -2,
    "trial_n": 167,
    "rews1a": -2,
    "rews1b": -2,
    "rews2a": -2,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -1,
    "trial_n": 168,
    "rews1a": -2,
    "rews1b": -1,
    "rews2a": -2,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -1,
    "trial_n": 169,
    "rews1a": -2,
    "rews1b": -1,
    "rews2a": -2,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -1,
    "trial_n": 170,
    "rews1a": -3,
    "rews1b": -1,
    "rews2a": -3,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": -1,
    "trial_n": 171,
    "rews1a": -3,
    "rews1b": -2,
    "rews2a": -2,
    "rews2b": -1,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -2,
    "trial_n": 172,
    "rews1a": -2,
    "rews1b": -1,
    "rews2a": -2,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -1,
    "trial_n": 173,
    "rews1a": -1,
    "rews1b": -2,
    "rews2a": -2,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -2,
    "trial_n": 174,
    "rews1a": 0,
    "rews1b": -2,
    "rews2a": -1,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -3,
    "trial_n": 175,
    "rews1a": -1,
    "rews1b": -3,
    "rews2a": -1,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -2,
    "trial_n": 176,
    "rews1a": 0,
    "rews1b": -2,
    "rews2a": 0,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 0,
    "trial_n": 177,
    "rews1a": 0,
    "rews1b": -3,
    "rews2a": 0,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -3,
    "trial_n": 178,
    "rews1a": 1,
    "rews1b": -3,
    "rews2a": 1,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 179,
    "rews1a": 2,
    "rews1b": -3,
    "rews2a": 2,
    "rews2b": -4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -2,
    "trial_n": 180,
    "rews1a": 2,
    "rews1b": -2,
    "rews2a": 1,
    "rews2b": -3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 181,
    "rews1a": 2,
    "rews1b": -2,
    "rews2a": 1,
    "rews2b": -4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 1,
    "re": 0,
    "trial_n": 182,
    "rews1a": 2,
    "rews1b": -2,
    "rews2a": 0,
    "rews2b": -5,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 183,
    "rews1a": 2,
    "rews1b": -2,
    "rews2a": 1,
    "rews2b": -4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": 1,
    "trial_n": 184,
    "rews1a": 1,
    "rews1b": -2,
    "rews2a": 1,
    "rews2b": -4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 185,
    "rews1a": 1,
    "rews1b": -2,
    "rews2a": 1,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 186,
    "rews1a": 1,
    "rews1b": -1,
    "rews2a": 0,
    "rews2b": -4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 187,
    "rews1a": 1,
    "rews1b": -1,
    "rews2a": -1,
    "rews2b": -4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 188,
    "rews1a": 1,
    "rews1b": -2,
    "rews2a": -1,
    "rews2b": -4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 189,
    "rews1a": 1,
    "rews1b": -2,
    "rews2a": -1,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 190,
    "rews1a": 1,
    "rews1b": -4,
    "rews2a": -1,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 3,
    "trial_n": 191,
    "rews1a": 3,
    "rews1b": -5,
    "rews2a": 0,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 3,
    "trial_n": 192,
    "rews1a": 3,
    "rews1b": -5,
    "rews2a": 1,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": 3,
    "trial_n": 193,
    "rews1a": 3,
    "rews1b": -5,
    "rews2a": 1,
    "rews2b": 0,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -4,
    "trial_n": 194,
    "rews1a": 2,
    "rews1b": -4,
    "rews2a": 1,
    "rews2b": 0,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 195,
    "rews1a": 1,
    "rews1b": -5,
    "rews2a": 1,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 196,
    "rews1a": 1,
    "rews1b": -5,
    "rews2a": 0,
    "rews2b": -1,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 2,
    "re": -4,
    "trial_n": 197,
    "rews1a": 1,
    "rews1b": -4,
    "rews2a": 1,
    "rews2b": -2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 198,
    "rews1a": 1,
    "rews1b": -4,
    "rews2a": 1,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 0,
    "trial_n": 199,
    "rews1a": 0,
    "rews1b": -3,
    "rews2a": 0,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 1,
    "trial_n": 200,
    "rews1a": 1,
    "rews1b": -3,
    "rews2a": -1,
    "rews2b": -3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 201,
    "rews1a": 2,
    "rews1b": -1,
    "rews2a": -2,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 4,
    "trial_n": 202,
    "rews1a": 4,
    "rews1b": -1,
    "rews2a": -1,
    "rews2b": -2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -1,
    "trial_n": 203,
    "rews1a": 4,
    "rews1b": -1,
    "rews2a": -1,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 4,
    "trial_n": 204,
    "rews1a": 4,
    "rews1b": -1,
    "rews2a": -2,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 3,
    "trial_n": 205,
    "rews1a": 3,
    "rews1b": -1,
    "rews2a": -1,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": -1,
    "trial_n": 206,
    "rews1a": 3,
    "rews1b": 0,
    "rews2a": -1,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 207,
    "rews1a": 2,
    "rews1b": 0,
    "rews2a": -1,
    "rews2b": 2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": 2,
    "trial_n": 208,
    "rews1a": 2,
    "rews1b": 1,
    "rews2a": -1,
    "rews2b": 2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 3,
    "trial_n": 209,
    "rews1a": 3,
    "rews1b": 1,
    "rews2a": -2,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -1,
    "trial_n": 210,
    "rews1a": 4,
    "rews1b": -1,
    "rews2a": -1,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 2,
    "c2": 1,
    "re": 4,
    "trial_n": 211,
    "rews1a": 4,
    "rews1b": -2,
    "rews2a": -1,
    "rews2b": 0,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 5,
    "trial_n": 212,
    "rews1a": 5,
    "rews1b": -3,
    "rews2a": 0,
    "rews2b": 0,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 4,
    "trial_n": 213,
    "rews1a": 4,
    "rews1b": -4,
    "rews2a": -1,
    "rews2b": -1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 3,
    "trial_n": 214,
    "rews1a": 3,
    "rews1b": -3,
    "rews2a": -2,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": 3,
    "trial_n": 215,
    "rews1a": 3,
    "rews1b": -3,
    "rews2a": 0,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -2,
    "trial_n": 216,
    "rews1a": 2,
    "rews1b": -2,
    "rews2a": -2,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 1,
    "trial_n": 217,
    "rews1a": 1,
    "rews1b": -2,
    "rews2a": -4,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": -4,
    "trial_n": 218,
    "rews1a": 0,
    "rews1b": -3,
    "rews2a": -4,
    "rews2b": 2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": -3,
    "trial_n": 219,
    "rews1a": -1,
    "rews1b": -2,
    "rews2a": -3,
    "rews2b": 2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 3,
    "trial_n": 220,
    "rews1a": -1,
    "rews1b": -2,
    "rews2a": -3,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 1,
    "trial_n": 221,
    "rews1a": -1,
    "rews1b": -1,
    "rews2a": -3,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 1,
    "trial_n": 222,
    "rews1a": -2,
    "rews1b": -2,
    "rews2a": -3,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -3,
    "trial_n": 223,
    "rews1a": -3,
    "rews1b": -1,
    "rews2a": -3,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 1,
    "trial_n": 224,
    "rews1a": -3,
    "rews1b": -2,
    "rews2a": -4,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 1,
    "trial_n": 225,
    "rews1a": -2,
    "rews1b": -1,
    "rews2a": -4,
    "rews2b": 1,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 1,
    "re": -5,
    "trial_n": 226,
    "rews1a": -1,
    "rews1b": -1,
    "rews2a": -5,
    "rews2b": 0,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 2,
    "trial_n": 227,
    "rews1a": -2,
    "rews1b": -1,
    "rews2a": -4,
    "rews2b": 2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": -5,
    "trial_n": 228,
    "rews1a": -4,
    "rews1b": -1,
    "rews2a": -5,
    "rews2b": 2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -5,
    "trial_n": 229,
    "rews1a": -5,
    "rews1b": -1,
    "rews2a": -4,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 3,
    "trial_n": 230,
    "rews1a": -4,
    "rews1b": -1,
    "rews2a": -3,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -3,
    "trial_n": 231,
    "rews1a": -3,
    "rews1b": -2,
    "rews2a": -3,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 3,
    "trial_n": 232,
    "rews1a": -3,
    "rews1b": -1,
    "rews2a": -1,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 1,
    "re": -2,
    "trial_n": 233,
    "rews1a": -2,
    "rews1b": -2,
    "rews2a": -2,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -4,
    "trial_n": 234,
    "rews1a": 0,
    "rews1b": -4,
    "rews2a": -2,
    "rews2b": 5,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -5,
    "trial_n": 235,
    "rews1a": -2,
    "rews1b": -5,
    "rews2a": -2,
    "rews2b": 5,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -5,
    "trial_n": 236,
    "rews1a": -2,
    "rews1b": -5,
    "rews2a": -2,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 237,
    "rews1a": -2,
    "rews1b": -4,
    "rews2a": -2,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 238,
    "rews1a": -2,
    "rews1b": -4,
    "rews2a": -2,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 239,
    "rews1a": 0,
    "rews1b": -4,
    "rews2a": -3,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -5,
    "trial_n": 240,
    "rews1a": -1,
    "rews1b": -5,
    "rews2a": -2,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -5,
    "trial_n": 241,
    "rews1a": -2,
    "rews1b": -5,
    "rews2a": -3,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -4,
    "trial_n": 242,
    "rews1a": -3,
    "rews1b": -4,
    "rews2a": -3,
    "rews2b": 2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -4,
    "trial_n": 243,
    "rews1a": -3,
    "rews1b": -4,
    "rews2a": -3,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 244,
    "rews1a": -3,
    "rews1b": -3,
    "rews2a": -2,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 4,
    "trial_n": 245,
    "rews1a": -3,
    "rews1b": -3,
    "rews2a": -4,
    "rews2b": 4,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 1,
    "re": -4,
    "trial_n": 246,
    "rews1a": -3,
    "rews1b": -3,
    "rews2a": -4,
    "rews2b": 3,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 1,
    "re": -5,
    "trial_n": 247,
    "rews1a": -3,
    "rews1b": -4,
    "rews2a": -5,
    "rews2b": 2,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 2,
    "s2": 3,
    "c2": 2,
    "re": 2,
    "trial_n": 248,
    "rews1a": -3,
    "rews1b": -4,
    "rews2a": -5,
    "rews2b": 2,
    "common": 1
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 3,
    "c2": 2,
    "re": 3,
    "trial_n": 249,
    "rews1a": -3,
    "rews1b": -4,
    "rews2a": -4,
    "rews2b": 3,
    "common": 0
  },
  {
    "sub_id": "hybrid_agent_1",
    "c1": 1,
    "s2": 2,
    "c2": 2,
    "re": -4,
    "trial_n": 250,
    "rews1a": -3,
    "rews1b": -4,
    "rews2a": -4,
    "rews2b": 3,
    "common": 1
  }
]