var practice_agent_data = [
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 2,
      "c2": 1,
      "re": 0,
      "trial_n": 1,
      "rews1a": 0,
      "rews1b": 1,
      "rews2a": 2,
      "rews2b": 0,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 3,
      "c2": 1,
      "re": 2,
      "trial_n": 2,
      "rews1a": 0,
      "rews1b": 0,
      "rews2a": 2,
      "rews2b": -5,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 3,
      "c2": 2,
      "re": -5,
      "trial_n": 3,
      "rews1a": -3,
      "rews1b": -1,
      "rews2a": 3,
      "rews2b": -5,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 3,
      "c2": 1,
      "re": 2,
      "trial_n": 4,
      "rews1a": -4,
      "rews1b": -1,
      "rews2a": 2,
      "rews2b": -4,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 3,
      "c2": 1,
      "re": 3,
      "trial_n": 5,
      "rews1a": -5,
      "rews1b": -1,
      "rews2a": 3,
      "rews2b": -4,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 2,
      "c2": 2,
      "re": -2,
      "trial_n": 6,
      "rews1a": -5,
      "rews1b": -2,
      "rews2a": 4,
      "rews2b": -4,
      "common": 0
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 3,
      "c2": 1,
      "re": 5,
      "trial_n": 7,
      "rews1a": -4,
      "rews1b": -2,
      "rews2a": 5,
      "rews2b": -2,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 3,
      "c2": 1,
      "re": 4,
      "trial_n": 8,
      "rews1a": -4,
      "rews1b": -1,
      "rews2a": 4,
      "rews2b": -2,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 3,
      "c2": 1,
      "re": 3,
      "trial_n": 9,
      "rews1a": -2,
      "rews1b": -2,
      "rews2a": 3,
      "rews2b": -2,
      "common": 0
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 2,
      "c2": 1,
      "re": -2,
      "trial_n": 10,
      "rews1a": -2,
      "rews1b": -2,
      "rews2a": 2,
      "rews2b": -1,
      "common": 0
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 3,
      "c2": 1,
      "re": 4,
      "trial_n": 11,
      "rews1a": -2,
      "rews1b": -3,
      "rews2a": 4,
      "rews2b": 0,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 3,
      "c2": 1,
      "re": 4,
      "trial_n": 12,
      "rews1a": 0,
      "rews1b": -3,
      "rews2a": 4,
      "rews2b": 1,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 3,
      "c2": 1,
      "re": 5,
      "trial_n": 13,
      "rews1a": -2,
      "rews1b": -4,
      "rews2a": 5,
      "rews2b": 1,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 2,
      "c2": 1,
      "re": -2,
      "trial_n": 14,
      "rews1a": -2,
      "rews1b": -3,
      "rews2a": 3,
      "rews2b": 1,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 3,
      "c2": 2,
      "re": 0,
      "trial_n": 15,
      "rews1a": -2,
      "rews1b": 0,
      "rews2a": 3,
      "rews2b": 0,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 2,
      "c2": 2,
      "re": -1,
      "trial_n": 16,
      "rews1a": -3,
      "rews1b": -1,
      "rews2a": 3,
      "rews2b": -1,
      "common": 0
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 2,
      "c2": 1,
      "re": -5,
      "trial_n": 17,
      "rews1a": -5,
      "rews1b": -2,
      "rews2a": 3,
      "rews2b": 0,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 3,
      "c2": 1,
      "re": 2,
      "trial_n": 18,
      "rews1a": -4,
      "rews1b": 1,
      "rews2a": 2,
      "rews2b": 2,
      "common": 0
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 3,
      "c2": 1,
      "re": 2,
      "trial_n": 19,
      "rews1a": -4,
      "rews1b": 0,
      "rews2a": 2,
      "rews2b": 3,
      "common": 0
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 2,
      "c2": 2,
      "re": -2,
      "trial_n": 20,
      "rews1a": -3,
      "rews1b": -2,
      "rews2a": 3,
      "rews2b": 4,
      "common": 0
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 2,
      "c2": 1,
      "re": -3,
      "trial_n": 21,
      "rews1a": -3,
      "rews1b": -3,
      "rews2a": 2,
      "rews2b": 3,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 2,
      "c2": 1,
      "re": -3,
      "trial_n": 22,
      "rews1a": -3,
      "rews1b": -3,
      "rews2a": 2,
      "rews2b": 3,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 3,
      "c2": 1,
      "re": 1,
      "trial_n": 23,
      "rews1a": -3,
      "rews1b": -5,
      "rews2a": 1,
      "rews2b": 2,
      "common": 0
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 2,
      "c2": 2,
      "re": -4,
      "trial_n": 24,
      "rews1a": -5,
      "rews1b": -4,
      "rews2a": -1,
      "rews2b": 2,
      "common": 0
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 3,
      "c2": 2,
      "re": 2,
      "trial_n": 25,
      "rews1a": -5,
      "rews1b": -4,
      "rews2a": 0,
      "rews2b": 2,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 2,
      "c2": 1,
      "re": -5,
      "trial_n": 26,
      "rews1a": -5,
      "rews1b": -5,
      "rews2a": 1,
      "rews2b": 3,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 2,
      "c2": 1,
      "re": -4,
      "trial_n": 27,
      "rews1a": -4,
      "rews1b": -4,
      "rews2a": 2,
      "rews2b": 4,
      "common": 1
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 3,
      "c2": 1,
      "re": 1,
      "trial_n": 28,
      "rews1a": -4,
      "rews1b": -3,
      "rews2a": 1,
      "rews2b": 4,
      "common": 0
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 3,
      "c2": 1,
      "re": 1,
      "trial_n": 29,
      "rews1a": -3,
      "rews1b": -4,
      "rews2a": 1,
      "rews2b": 4,
      "common": 0
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 2,
      "c2": 1,
      "re": -2,
      "trial_n": 30,
      "rews1a": -2,
      "rews1b": -3,
      "rews2a": 2,
      "rews2b": 5,
      "common": 0
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 1,
      "s2": 3,
      "c2": 1,
      "re": 2,
      "trial_n": 31,
      "rews1a": -1,
      "rews1b": -3,
      "rews2a": 2,
      "rews2b": 4,
      "common": 0
    },
    {
      "sub_id": "practice_hybrid_agent_1",
      "c1": 2,
      "s2": 3,
      "c2": 2,
      "re": 4,
      "trial_n": 32,
      "rews1a": -1,
      "rews1b": 0,
      "rews2a": 2,
      "rews2b": 4,
      "common": 1
    }
  ]