
rm(list = ls())


#load packages
if (!require(devtools)) {install.packages("devtools"); require(devtools)} 
if (!require(tidyverse)) {install.packages("tidyverse"); require(tidyverse)}
if (!require(ggplot2)) {install.packages("ggplot2"); require(ggplot2)} 
if (!require(ggpubr)) {install.packages("ggpubr"); require(ggpubr)} 
if (!require(ggstatsplot)) {install_github("IndrajeetPatil/ggstatsplot");
  require(ggstatsplot)}
if (!require(rmarkdown)) {install.packages("rmarkdown"); require(rmarkdown)} 
if (!require(gridExtra)) {install.packages("gridExtra"); require(gridExtra)} 


#set working directory to the directory where script is residing 
groupedstats:::set_cwd()


#PART ONE (SIMULATIONS 3.1)
##comparing fit for data generated by correct model

sims3.1.correct.model <- read_csv('AIC_simulations_3_1_correct_model.csv')
sims3.1.wrong.model <- read_csv('AIC_simulations_3_1_wrong_model.csv')


df.sims3.1 <- data.frame(
  sub_id = integer(2000),
  model = integer(2000),
  AIC_score = double(2000)
)

df.sims3.1[1:1000,]$sub_id<- sims3.1.correct.model$sub_id
df.sims3.1[1:1000,]$model <- 1
df.sims3.1[1:1000,]$AIC_score <- sims3.1.correct.model$AIC

df.sims3.1[1001:2000,]$sub_id<- sims3.1.wrong.model$sub_id
df.sims3.1[1001:2000,]$model <- 0
df.sims3.1[1001:2000,]$AIC_score <- sims3.1.wrong.model$AIC

df.sims3.1$model <- factor(df.sims3.1$model, levels = c(1,0), labels = c('Correct Model', 'Wrong Model'))
table(df.sims3.1$model)#confirm that it works 
head(df.sims3.1)

#visualize 
df.sims3.1 %>%
  ggplot(aes(x = AIC_score, fill = model)) +
  geom_histogram( color="#e9ecef", alpha=0.8, position = 'identity', binwidth = 5) + 
  scale_fill_manual(values=c("#69b3a2", "#404080")) +
  theme_classic() + 
  labs(fill = "Model:",
       x = "AIC scores",
       y = "Count") + 
  theme(legend.position = 'bottom') 

#psych describe scores

psych::describeBy(df.sims3.1$AIC_score, df.sims3.1$model)


#PART ONE (SIMULATIONS 3.2)
##comparing fit for data generated by wrong model

sims3.2.correct.model <- read_csv('AIC_simulations_3_2_correct_model.csv')
sims3.2.wrong.model <- read_csv('AIC_simulations_3_2_wrong_model.csv')

df.sims3.2 <- data.frame(
  sub_id = integer(2000),
  model = integer(2000),
  AIC_score = double(2000)
)

df.sims3.2[1:1000,]$sub_id<- sims3.2.correct.model$sub_id
df.sims3.2[1:1000,]$model <- 1
df.sims3.2[1:1000,]$AIC_score <- sims3.2.correct.model$AIC

df.sims3.2[1001:2000,]$sub_id<- sims3.2.wrong.model$sub_id
df.sims3.2[1001:2000,]$model <- 0
df.sims3.2[1001:2000,]$AIC_score <- sims3.2.wrong.model$AIC

df.sims3.2$model <- factor(df.sims3.2$model, levels = c(1,0), labels = c('Correct Model', 'Wrong Model'))
table(df.sims3.2$model)#confirm that it works 
head(df.sims3.2)

#visualize 
df.sims3.2 %>%
  ggplot(aes(x = AIC_score, fill = model)) +
  geom_histogram( color="#e9ecef", alpha=0.8, position = 'identity', binwidth = 5) + 
  scale_fill_manual(values=c("#69b3a2", "#404080")) +
  theme_classic() + 
  labs(fill = "Model:",
       x = "AIC scores",
       y = "Count") + 
  theme(legend.position = 'bottom') 

#psych describe scores

psych::describeBy(df.sims3.2$AIC_score, df.sims3.2$model)


#PART ONE (SIMULATIONS 3.3)
# generating model-based agents

sims3.3.fit.params <- read_csv('simulations_3_3_fit_params_correct_model.csv')
head(sims3.3.fit.params)
#visualize 
sims3.3.fit.params %>%
  ggplot(aes(x = w_MB,)) +
  geom_histogram(fill = "#404080", color="#e9ecef", alpha=0.8, position = 'identity', binwidth = .025) + 
  theme_classic() + 
  labs(x = "w weight",
       y = "Count") + 
  theme(legend.position = 'bottom') 

#psych describe to compare AIC scores 
psych::describe(sims3.3.fit.params$w_MB)



#SIMULATIONS 3.4
#study1

df.study1.correct.model <- read_csv('AIC_simulations_3_study1_correct_model.csv')
df.study1.wrong.model <- read_csv('AIC_simulations_3_study1_wrong_model.csv')

df.study1 <- data.frame(
  sub_id = integer(77*2),
  model = integer(77*2),
  AIC_score = double(77*2)
)

df.study1[1:77,]$sub_id <- df.study1.correct.model$sub_id
df.study1[1:77,]$model <- 1
df.study1[1:77,]$AIC_score <- df.study1.correct.model$AIC

df.study1[78:154,]$sub_id <- df.study1.wrong.model$sub_id
df.study1[78:154,]$model <- 0 
df.study1[78:154,]$AIC_score <- df.study1.wrong.model$AIC


df.study1$model <- factor(df.study1$model, levels = c(1,0), labels = c('Correct Model', 'Wrong Model'))
table(df.study1$model)#confirm that it works 
head(df.study1)


#visualize 
df.study1 %>%
  ggplot(aes(x = AIC_score, fill = model)) +
  geom_histogram( color="#e9ecef", alpha=0.8, position = 'identity', binwidth = 2.5) + 
  scale_fill_manual(values=c("#69b3a2", "#404080")) +
  theme_classic() + 
  labs(fill = "Model:",
       x = "AIC scores",
       y = "Count") + 
  theme(legend.position = 'bottom') 

#psych describe scores

psych::describeBy(df.study1$AIC_score, df.study1$model)


#study2

df.study2.correct.model <- read_csv('AIC_simulations_3_study2_correct_model.csv')
df.study2.wrong.model <- read_csv('AIC_simulations_3_study2_wrong_model.csv')

df.study2 <- data.frame(
  sub_id = integer(172*2),
  model = integer(172*2),
  AIC_score = double(172*2)
)

df.study2[1:172,]$sub_id <- df.study2.correct.model$sub_id
df.study2[1:172,]$model <- 1
df.study2[1:172,]$AIC_score <- df.study2.correct.model$AIC

df.study2[173:344,]$sub_id <- df.study2.wrong.model$sub_id
df.study2[173:344,]$model <- 0 
df.study2[173:344,]$AIC_score <- df.study2.wrong.model$AIC


df.study2$model <- factor(df.study2$model, levels = c(1,0), labels = c('Correct Model', 'Wrong Model'))
table(df.study2$model)#confirm that it works 
head(df.study2)


#visualize 
df.study2 %>%
  ggplot(aes(x = AIC_score, fill = model)) +
  geom_histogram( color="#e9ecef", alpha=0.8, position = 'identity', binwidth = 5) + 
  scale_fill_manual(values=c("#69b3a2", "#404080")) +
  theme_classic() + 
  labs(fill = "Model:",
       x = "AIC scores",
       y = "Count") + 
  theme(legend.position = 'bottom') 

#psych describe scores

psych::describeBy(df.study2$AIC_score, df.study2$model)


